# Generated by Django 3.1 on 2020-08-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200817_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='image',
        ),
        migrations.CreateModel(
            name='RugImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rugs')),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rug')),
            ],
        ),
    ]
