# Generated by Django 3.1 on 2020-08-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200817_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='height_inch',
            field=models.IntegerField(blank=True, verbose_name='Height Inch X"'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='priceUSD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='width_inch',
            field=models.IntegerField(blank=True, verbose_name='Width Inch X"'),
        ),
        migrations.AlterField(
            model_name='rugimage',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.rug'),
        ),
    ]
