# Generated by Django 3.1 on 2020-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200817_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='sku',
            field=models.CharField(max_length=255, verbose_name='SKU'),
        ),
    ]
