# Generated by Django 3.1 on 2020-08-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200817_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rug',
            old_name='priceUSD',
            new_name='price_usd',
        ),
        migrations.AddField(
            model_name='rug',
            name='price_usd_after_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)'),
        ),
    ]
