# Generated by Django 3.1 on 2020-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200817_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='price_usd_after_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD) After Sale'),
        ),
    ]
