# Generated by Django 3.1 on 2020-08-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200821_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugimage',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='image', to='api.rug'),
        ),
    ]
