# Generated by Django 3.1 on 2020-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200821_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='name',
            field=models.CharField(blank=True, help_text='Only fill when style is not found in a list.', max_length=256, null=True, verbose_name='Name (Optional)'),
        ),
    ]
