# Generated by Django 3.1 on 2020-08-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200823_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rugvariation',
            options={'ordering': ['rug', 'width_feet']},
        ),
    ]
