# Generated by Django 3.1 on 2020-08-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200825_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugimage',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.rug'),
        ),
        migrations.AlterField(
            model_name='rugvariation',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='api.rug'),
        ),
    ]
