# Generated by Django 3.1 on 2020-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200914_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
