# Generated by Django 3.1 on 2020-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_address_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('is_primary',)},
        ),
    ]
