# Generated by Django 3.1 on 2020-09-18 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0043_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rug_variation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.rugvariation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rug'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
