# Generated by Django 3.1 on 2020-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200922_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='In',
            field=models.IntegerField(default=75, verbose_name='Insurance (price)'),
        ),
    ]
