# Generated by Django 3.1 on 2020-09-28 20:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200922_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rug',
            old_name='es',
            new_name='ES',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='gs',
            new_name='GS',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='In',
            new_name='IN',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='sr',
            new_name='SR',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='wc',
            new_name='WC',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='wg',
            new_name='WG',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selecteds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN', 'Insurance'), ('SR', 'Signature Release Required'), ('WG', 'White Glove Delivery'), ('WC', 'Will-Call Pick Up'), ('GS', 'Ground Shipping'), ('ES', 'Expedited Shipping')], max_length=2), blank=True, default=None, null=True, size=3),
        ),
    ]
