# Generated by Django 3.1 on 2020-09-28 20:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200928_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selecteds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN', 'Insurance'), ('SR', 'Signature Release Required'), ('WG', 'White Glove Delivery'), ('WC', 'Will-Call Pick Up'), ('GS', 'Ground Shipping'), ('ES', 'Expedited Shipping')], max_length=2), blank=True, default=None, null=True, size=6),
        ),
    ]
