# Generated by Django 3.1 on 2020-10-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20201002_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rugvariation',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
