# Generated by Django 3.1 on 2020-10-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='forecasted_arrival',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
