# Generated by Django 3.1 on 2020-10-07 18:28

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20201006_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selecteds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN', 'Insurance'), ('SR', 'Signature Release Required'), ('WG', 'White Glove Delivery'), ('WC', 'Will-Call Pick Up'), ('GS', 'Ground Shipping'), ('ES', 'Expedited Shipping')], max_length=2), default=api.models.AbstractCartItem.default_selecteds, help_text='IN - Insurance | SR - Signature Release Required | WG - White Glove Delivery | WC - Will-Call Pick Up | GS - Ground Shipping | ES - Expedited Shipping', size=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='selecteds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN', 'Insurance'), ('SR', 'Signature Release Required'), ('WG', 'White Glove Delivery'), ('WC', 'Will-Call Pick Up'), ('GS', 'Ground Shipping'), ('ES', 'Expedited Shipping')], max_length=2), default=api.models.AbstractCartItem.default_selecteds, help_text='IN - Insurance | SR - Signature Release Required | WG - White Glove Delivery | WC - Will-Call Pick Up | GS - Ground Shipping | ES - Expedited Shipping', size=6),
        ),
    ]
