# Generated by Django 3.1 on 2020-10-11 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20201010_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='order_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None),
        ),
    ]
