# Generated by Django 3.1 on 2020-10-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20201021_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='RugGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='rug-groups')),
                ('parent_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ruggroup')),
            ],
        ),
        migrations.AlterField(
            model_name='rug',
            name='style',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ruggroup', verbose_name='Style*'),
        ),
    ]
