# Generated by Django 3.1 on 2020-10-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20201023_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='style',
        ),
        migrations.AddField(
            model_name='rug',
            name='group_by_age',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rug_a', to='api.ruggroup', verbose_name='Group by Age*'),
        ),
        migrations.AddField(
            model_name='rug',
            name='group_by_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ruggroup', verbose_name='Group by Type*'),
        ),
    ]
