# Generated by Django 3.1 on 2020-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20201023_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruggroup',
            name='type',
            field=models.CharField(choices=[('a', 'Age (e.g. Vintage)'), ('t', 'Type (e.g. Runner)')], default='a', max_length=1),
        ),
    ]
