# Generated by Django 3.1 on 2020-10-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20201025_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rug',
            name='base_price_after_sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rug',
            name='base_price_before_sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rug',
            name='group_by_age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rug_a', to='api.ruggroup', verbose_name='Group by Age (e.g. Vintage)'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='group_by_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ruggroup', verbose_name='Group by Type (e.g. Runner)'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rug',
            name='sku',
            field=models.CharField(max_length=255),
        ),
    ]
