# Generated by Django 3.1 on 2020-10-26 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20201025_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruggroup',
            name='tree_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
