# Generated by Django 3.1 on 2020-10-26 11:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_ruggroup_tree_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruggroup',
            name='tree_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None, verbose_name='tree_ids (FILLED AUTOMATICALLY)'),
        ),
    ]
