# Generated by Django 3.1 on 2020-10-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20201026_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruggroup',
            name='tree_ids',
        ),
    ]
