# Generated by Django 3.1 on 2020-10-26 16:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_ruggroup_tree_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruggroup',
            name='tree_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='tree_ids (FILLED AUTOMATICALLY)'),
        ),
        migrations.AlterField(
            model_name='rugimage',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='api.rug'),
        ),
        migrations.AlterField(
            model_name='rugvariation',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', related_query_name='variations', to='api.rug'),
        ),
    ]
