# Generated by Django 3.1 on 2020-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20201026_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='rugvariation',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
