# Generated by Django 3.1 on 2020-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_rugvariation_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rugvariation',
            name='display',
        ),
    ]
