version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yfgNc2#7Eh6mUqtl
  backend:
    build: ./setup2
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./setup2:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./setup2/frontend
    command: npm run dev
    volumes:
      - ./setup2:/code