# Generated by Django 3.1 on 2020-08-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name="Rug's Name")),
                ('width_feet', models.IntegerField(verbose_name='Width (Feet)')),
                ('height_feet', models.IntegerField(verbose_name='Height (Feet)')),
                ('style', models.IntegerField(choices=[(0, '****Antique****'), (1, 'Persian'), (2, 'Armenian / Caucasian'), (3, 'Khotan / Samerkand'), (4, 'Turkish'), (5, 'Turqish Kilim'), (6, 'Indian'), (7, 'European'), (8, 'Chinese'), (9, 'Inspired / Recreation'), (10, '****Vintage****'), (11, 'Moroccan'), (4, 'Turkish'), (13, '****Contemporary****'), (14, 'Moroccan High Atlas'), (15, 'Modern'), (16, '****Other****'), (17, 'Afghan / Balouch'), (18, 'Gallery-Size Rugs'), (19, 'Furniture / Accessories')], verbose_name='Style (e.g. Moroccan)')),
                ('image', models.ImageField(upload_to='rugs')),
                ('priceUSD', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (USD)')),
                ('desc', models.TextField(verbose_name='Description')),
                ('quanity', models.IntegerField(verbose_name='Quanity (Available)')),
                ('sku', models.IntegerField(verbose_name='SKU')),
            ],
        ),
    ]
