# Generated by Django 3.1 on 2020-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200817_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='height_inch',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height Inch X"'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='width_inch',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width Inch X"'),
        ),
    ]
