# Generated by Django 3.1 on 2020-08-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200817_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='height_feet',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='height_inch',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='price_usd_after_sale',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='quanity',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='width_feet',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='width_inch',
        ),
        migrations.CreateModel(
            name='RugVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_feet', models.IntegerField(verbose_name="Width Feet X'")),
                ('width_inch', models.IntegerField(blank=True, null=True, verbose_name='Width Inch X"')),
                ('height_feet', models.IntegerField(verbose_name="Height Feet X'")),
                ('height_inch', models.IntegerField(blank=True, null=True, verbose_name='Height Inch X"')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price (USD)')),
                ('price_usd_after_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD) After Sale')),
                ('quanity', models.IntegerField(default=1, verbose_name='Quanity (Available)')),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rug')),
            ],
        ),
    ]
