# Generated by Django 3.1 on 2020-08-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rugvariation_is_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugvariation',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='Is Sample'),
        ),
        migrations.AlterField(
            model_name='rugvariation',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='api.rug'),
        ),
    ]
