# Generated by Django 3.1 on 2020-08-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200819_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugimage',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rug'),
        ),
        migrations.AlterField(
            model_name='rugvariation',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rug'),
        ),
    ]
