# Generated by Django 3.1 on 2020-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200821_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='rug',
            name='base_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Base Price (LEAVE EMPTY)'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name (LEAVE EMPTY)'),
        ),
    ]
