# Generated by Django 3.1 on 2020-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200821_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rug',
            name='name',
            field=models.CharField(blank=True, help_text='Only fill when style is not found in a list', max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='style',
            field=models.IntegerField(blank=True, choices=[(0, '****Antique****'), (1, 'Khotan'), (2, 'Samarkand'), (3, 'Chinese'), (4, 'Afghan'), (5, 'Balouch'), (6, 'Afshar'), (7, 'Turkaman'), (8, 'Ersari'), (9, 'Bukara'), (10, 'Tekke'), (11, '****Antique Persian****'), (12, 'Malayer'), (13, 'Tabriz'), (14, 'Sultanabad'), (15, 'Mahal'), (15, 'Mahal'), (17, 'Farahan'), (18, 'Kerman'), (19, 'Khorassan'), (20, 'Heriz'), (21, 'Serapi'), (22, 'Sarab / Camel'), (23, 'Bakhshaish'), (24, 'Bakhtiari'), (25, 'Bidjar'), (26, '****Persian Traditional****'), (27, 'Kashan'), (28, 'Mashad'), (29, 'Isfahan'), (30, 'Tehran'), (31, 'Qum'), (32, 'Nain'), (33, '****Antique Armenian / Caucasian****'), (34, 'Karabagh'), (35, 'Soumack'), (36, 'Shirvan'), (37, 'Caucasian'), (38, 'Kazak'), (39, '****Antique Turkish****'), (40, 'Ghiordes'), (41, 'Sivas'), (42, 'Hereke'), (43, 'Kaysari'), (44, 'Kilim'), (45, 'Oushak'), (46, '****Antique Indian****'), (47, 'Agra'), (48, 'Amritsar'), (49, 'Dhurrie'), (50, 'Kashmir'), (51, 'Lahour'), (52, 'Larestan'), (53, '****Antique European****'), (54, 'Tapestery'), (55, 'French Deco'), (56, 'French Aubusson'), (57, 'French Savonerrie'), (58, 'Spanish'), (59, 'Donegal'), (60, 'Arts and Crafts'), (61, 'Bessarabian / Ukrainian'), (62, 'Italian Textile'), (63, '****Contemporary Moroccan****'), (64, 'High Atlas Collection'), (65, 'African Tuareg Mat'), (66, '****Other Contemporary Rugs****'), (67, 'Antique Inspired / Recreation'), (68, 'Swedish / Scandinavian Recreation'), (69, 'Modern'), (70, 'Modern Flat Weave'), (71, 'Afghan Modern Flat Weave'), (72, '****Vintage****'), (73, 'Turkish'), (74, 'Kilim / Flat Weave'), (75, 'Over-Dyed Distressed'), (76, 'Tulu'), (77, 'Morrocan'), (78, '****Vintage Swedish / Scandinavian****'), (79, 'Ingegerd'), (80, 'Marta Mass Fjetterstrom'), (81, 'Judith'), (82, 'Swedish'), (83, 'Scandinavian'), (84, '****Other****'), (85, 'Saddle Bags'), (86, 'Gallery-Size'), (87, 'Furniture / Accessories'), (88, 'Sustainable'), (89, 'Decorative'), (90, 'Ethnic'), (91, 'Traditional'), (92, 'Natural & Broad Loom'), (93, 'Custom Order')], null=True, verbose_name='Style (e.g. Moroccan)'),
        ),
    ]
