# Generated by Django 3.1 on 2020-08-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200821_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugvariation',
            name='rug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='variations', to='api.rug'),
        ),
    ]
