# Generated by Django 3.1 on 2020-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200821_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rug',
            name='base_price_after_sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='(LEAVE EMPTY)'),
        ),
        migrations.AddField(
            model_name='rug',
            name='base_price_before_sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='(LEAVE EMPTY)'),
        ),
        migrations.AlterField(
            model_name='rug',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='(LEAVE EMPTY)'),
        ),
    ]
