# Generated by Django 3.1 on 2020-08-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200825_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='height_largest',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='height_smallest',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='width_largest',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='width_smallest',
        ),
    ]
