# Generated by Django 3.1 on 2020-09-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pendinguserpersonalinfoupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguserpersonalinfoupdate',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('f', 'finished')], default='p', max_length=1),
        ),
    ]
