# Generated by Django 3.1 on 2020-09-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200917_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_primary',)},
        ),
    ]
