# Generated by Django 3.1 on 2020-09-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200917_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='RugShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('WC', 'Will-Call Pick Up'), ('GS', 'Ground Shipping')], db_column='type', max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='shipping_methods', to='api.rug')),
            ],
        ),
        migrations.CreateModel(
            name='RugAdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('IN', 'Insurance'), ('ES', 'Expedited Shipping'), ('SR', 'Signature Release Required'), ('WG', 'White Glove Delivery')], db_column='type', max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='additional_services', to='api.rug')),
            ],
        ),
    ]
