# Generated by Django 3.1 on 2020-10-06 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_checkoutsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cartitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.cartitem')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=6)),
                ('forecasted_arrival', models.DateTimeField(default=None, null=True)),
                ('tracking_url', models.URLField(default=None, null=True)),
                ('delivery_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.address')),
            ],
            bases=('api.cartitem',),
        ),
    ]
