# Generated by Django 3.1 on 2020-10-06 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_checkoutsession_order_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='order_model',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='order_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
    ]
