# Generated by Django 3.1 on 2020-10-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20201006_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
