# Generated by Django 3.1 on 2020-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('i', 'In Shop'), ('s', 'Sent'), ('d', 'Delivered')], default='i', max_length=1),
        ),
    ]
