# Generated by Django 3.1 on 2020-10-12 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20201011_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='rug_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='order_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list, size=None),
        ),
    ]
