# Generated by Django 3.1 on 2020-10-12 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20201012_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
