# Generated by Django 3.1 on 2020-10-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_checkoutsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='stripe_payment_intent_id',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='stripe_checkout_sess_id',
            field=models.CharField(max_length=100),
        ),
    ]
