# Generated by Django 3.1 on 2020-10-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20201012_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugimage',
            name='image',
            field=models.ImageField(default='default-rug.png', upload_to='rugs'),
        ),
    ]
