# Generated by Django 3.1 on 2020-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('n', 'Not Reviewed'), ('r', 'Reviewed')], default='n', max_length=1),
            preserve_default=False,
        ),
    ]
