- name: Docker Deployment
  # You may pin to the exact commit or the version.
  # uses: wshihadeh/docker-deployment-action@166354ab4bd0a28ad27760df5f69b97ea4cc9399
  uses: wshihadeh/docker-deployment-action@v1
  with:
    # Remote Docker host ie (user@host)
    remote_docker_host: 
    # Remote Docker SSH public key
    ssh_public_key: 
    # SSH private key used to connect to the docker host
    ssh_private_key: 
    # Deployment command args.
    args: 
    # Deployment mode either docker-swarm or docker-compose. Default is docker-compose.
    deployment_mode: # optional
    # Copy stack file to remote server and deploy from the server. Default is false.
    copy_stack_file: # optional
    # The path where the stack files will be copied to. Default ~/docker-deployment.
    deploy_path: # optional
    # Docker stack file used. Default is docker-compose.yaml
    stack_file_name: # optional
    # Number of the files to be kept on the server. Default is 3.
    keep_files: # optional
    # A boolean input to trigger docker prune command.
    docker_prune: # optional
    # The args for the pre deploument command.
    pre_deployment_command_args: # optional
    # Pull docker images before deploying.
    pull_images_first: # optional
